import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "bn";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.home": "Home",
    "nav.about": "About",
    "nav.services": "Services",
    "nav.work": "Work",
    "nav.team": "Team",
    "nav.contact": "Contact",
    "nav.startProject": "Start a Project",
    
    // Home Page
    "home.badge": "Creative Design & IT Agency",
    "home.title1": "Starting every idea from",
    "home.title2": "zero",
    "home.tagline": "From zero to impact",
    "home.description": "A creative IT agency focused on graphic design, web solutions, and visual identity. We help brands start from scratch and grow with clean, modern, and impactful design solutions.",
    "home.cta1": "Start Your Project",
    "home.cta2": "View Our Work",
    "home.stats.projects": "Projects Delivered",
    "home.stats.clients": "Happy Clients",
    "home.stats.years": "Years Experience",
    "home.stats.satisfaction": "Client Satisfaction",
    "home.expertise": "Our Expertise",
    "home.whatWeDo": "What we",
    "home.do": "do",
    "home.expertiseDesc": "Full-stack creative services to build and grow your digital presence",
    "home.whyChoose": "Why Choose AlphaZero",
    "home.builtFor": "Built for",
    "home.yourSuccess": "your success",
    "home.testimonials": "Testimonials",
    "home.whatClientsSay": "What our clients",
    "home.say": "say",
    "home.trustedBy": "Trusted by innovative brands",
    "home.letsBuild": "Let's build your",
    "home.brand": "brand",
    "home.readyTo": "Ready to transform your ideas into powerful visual experiences?",
    "home.freeConsultation": "Get a Free Consultation",
    "home.whatsappUs": "WhatsApp Us",
    "home.viewAllServices": "View All Services",
    
    // Services
    "home.service.uiux": "UI/UX Design",
    "home.service.uiuxDesc": "Intuitive interfaces that users love",
    "home.service.seo": "SEO Optimization",
    "home.service.seoDesc": "Get found by your target audience",
    "home.service.web": "Website Design & Development",
    "home.service.webDesc": "Fast, responsive, modern websites",
    "home.service.ecommerce": "E-commerce Solutions",
    "home.service.ecommerceDesc": "Sell online with powerful stores",
    "home.service.social": "Social Media Design",
    "home.service.socialDesc": "Engaging content that converts",
    "home.service.branding": "Branding & Creative Design",
    "home.service.brandingDesc": "Build memorable brand identity",
    
    // Why Choose Us
    "home.why.clean": "Clean & Modern Design",
    "home.why.cleanDesc": "Fresh, contemporary aesthetics that stand out",
    "home.why.brand": "Brand-Focused Strategy",
    "home.why.brandDesc": "Every design serves your brand's unique vision",
    "home.why.detail": "Detail-Oriented",
    "home.why.detailDesc": "Pixel-perfect execution on every project",
    "home.why.client": "Client-First Communication",
    "home.why.clientDesc": "Clear, responsive, and collaborative process",
    "home.why.zero": "Zero to Full Identity",
    "home.why.zeroDesc": "Complete brand solutions from scratch",
    
    // About Page
    "about.subtitle": "About Us",
    "about.title": "We are",
    "about.description": "A creative agency focused on graphic design, branding, and visual identity. We help brands start from scratch and grow with clean, modern, and impactful design solutions.",
    "about.story.badge": "Our Journey",
    "about.story.title": "The",
    "about.story.title2": "Story",
    "about.story.card1.title": "From Zero to Hero",
    "about.story.card1.desc": "AlphaZero is a creative agency focused on graphic design, branding, and visual identity. We believe every great brand starts from zero — and with the right vision and execution, it can make a lasting impact.",
    "about.story.card2.title": "Evolving Digital Excellence",
    "about.story.card2.desc": "Currently, AlphaZero delivers professional design services while evolving toward IT and AI-driven digital services. Our goal is to turn ideas into strong visual experiences that actually work.",
    "about.story.card3.title": "Client-First Approach",
    "about.story.card3.desc": "We prioritize understanding your vision and delivering solutions that exceed expectations. Your success is our success.",
    "about.tagline": "From Zero to Impact",
    "about.badge.agency": "Creative Agency",
    "about.whyChoose": "Why Choose AlphaZero?",
    "about.why1": "Clean and modern design approach",
    "about.why2": "Brand-focused visual strategy",
    "about.why3": "Detail-oriented workflow",
    "about.why4": "Client-first communication",
    "about.why5": "From zero to full identity support",
    "about.values.title": "Our Values",
    "about.values.subtitle": "The principles that guide everything we do",
    "about.values.brandFocused": "Brand-Focused",
    "about.values.brandFocusedDesc": "Every design decision serves your brand's unique identity and goals.",
    "about.values.zeroToImpact": "Zero to Impact",
    "about.values.zeroToImpactDesc": "We start from scratch and build powerful, impactful visual identities.",
    "about.values.globalReach": "Global Reach",
    "about.values.globalReachDesc": "Based in Bangladesh, delivering design solutions worldwide.",
    "about.location.title": "Based in Bangladesh",
    "about.location.address": "Bornali, Rajshahi, Bangladesh – 6000",
    "about.location.desc": "Working with clients worldwide, delivering impactful design solutions remotely.",
    "about.location.cta1": "Let's Connect",
    "about.location.cta2": "WhatsApp Us",
    
    // Team Page
    "team.subtitle": "Our Team",
    "team.title": "Meet the",
    "team.title2": "Creators",
    "team.description": "A passionate team of designers and developers dedicated to bringing your vision to life.",
    "team.join.title": "Want to join our team?",
    "team.join.desc": "We're always looking for talented individuals to join our creative family.",
    "team.join.cta1": "Apply Now",
    "team.join.cta2": "Contact Us",
    
    // Footer
    "footer.description": "AlphaZero is a creative design agency crafting modern visual identities and brand experiences. From zero to impact.",
    "footer.quickLinks": "Quick Links",
    "footer.contact": "Contact",
    "footer.rights": "All rights reserved.",
    "footer.ready": "Ready to create?",
    "footer.letsCreate": "Let's create something",
    "footer.together": "amazing together",
    "footer.navigation": "Navigation",
    "footer.social": "Social",
    
    // Common
    "common.learnMore": "Learn More",
    "common.viewAll": "View All",
    
    // Services Page
    "services.subtitle": "Our Services",
    "services.title": "Full-Stack",
    "services.title2": "Creative",
    "services.title3": "Services",
    "services.description": "From design to development, we provide comprehensive solutions to build and grow your digital presence.",
    "services.whatWeOffer": "What We Offer",
    "services.whatWeOfferDesc": "Agency-level services designed to take your brand from zero to impact",
    "services.graphicDesign": "Graphic Design Services",
    "services.videoEditing": "Video Editing Services",
    "services.digitalMarketing": "Digital Marketing Services",
    "services.computerOperation": "Computer Operation Services",
    "services.process.title": "Our Process",
    "services.process.desc": "A simple, effective approach to deliver impactful results",
    "services.process.discover": "Discover",
    "services.process.discoverDesc": "Understanding your brand, goals, and vision",
    "services.process.design": "Design",
    "services.process.designDesc": "Creating concepts and visual solutions",
    "services.process.develop": "Develop",
    "services.process.developDesc": "Building with precision and care",
    "services.process.deliver": "Deliver",
    "services.process.deliverDesc": "Final files and ongoing support",
    "services.cta.title": "Ready to start your project?",
    "services.cta.desc": "Let's discuss how we can help bring your vision to life.",
    "services.cta.button": "Get a Free Consultation",
    "services.cta.whatsapp": "WhatsApp Us",
    
    // Service Items
    "service.uiux.title": "UI/UX Design",
    "service.uiux.desc": "Create intuitive, user-centered interfaces that delight users and drive conversions.",
    "service.seo.title": "SEO Optimization",
    "service.seo.desc": "Boost your visibility and rank higher on search engines with data-driven strategies.",
    "service.web.title": "Website Design & Development",
    "service.web.desc": "Build fast, responsive, and modern websites that represent your brand perfectly.",
    "service.ecommerce.title": "E-commerce Website Design",
    "service.ecommerce.desc": "Launch your online store with powerful, conversion-focused e-commerce solutions.",
    "service.social.title": "Social Media Design & Management",
    "service.social.desc": "Create engaging content that builds community and drives brand awareness.",
    "service.branding.title": "Branding & Creative Design",
    "service.branding.desc": "Develop memorable brand identities that stand out in the market.",
    "service.video.title": "Video Editing",
    "service.video.desc": "Professional video editing services for promotional, social media, and corporate content.",
    "service.marketing.title": "Digital Marketing",
    "service.marketing.desc": "Grow your business with strategic digital marketing campaigns that drive results.",
    "service.computer.title": "Computer Operation",
    "service.computer.desc": "Expert computer operation services including MS Office, data entry, and document management.",
    
    // Service Features
    "feature.userResearch": "User Research",
    "feature.wireframing": "Wireframing",
    "feature.prototyping": "Prototyping",
    "feature.userTesting": "User Testing",
    "feature.keywordResearch": "Keyword Research",
    "feature.onPageSeo": "On-Page SEO",
    "feature.technicalSeo": "Technical SEO",
    "feature.analytics": "Analytics",
    "feature.customDesign": "Custom Design",
    "feature.responsiveLayout": "Responsive Layout",
    "feature.cmsIntegration": "CMS Integration",
    "feature.performance": "Performance",
    "feature.productCatalog": "Product Catalog",
    "feature.paymentGateway": "Payment Gateway",
    "feature.inventorySystem": "Inventory System",
    "feature.contentStrategy": "Content Strategy",
    "feature.postDesign": "Post Design",
    "feature.storyTemplates": "Story Templates",
    "feature.brandGuidelines": "Brand Guidelines",
    "feature.logoDesign": "Logo Design",
    "feature.brandIdentity": "Brand Identity",
    "feature.styleGuide": "Style Guide",
    "feature.marketingMaterials": "Marketing Materials",
    "feature.promotionalVideos": "Promotional Videos",
    "feature.socialMediaReels": "Social Media Reels",
    "feature.motionGraphics": "Motion Graphics",
    "feature.colorGrading": "Color Grading",
    "feature.socialMediaAds": "Social Media Ads",
    "feature.googleAds": "Google Ads",
    "feature.emailMarketing": "Email Marketing",
    "feature.contentMarketing": "Content Marketing",
    "feature.msOfficeExpert": "MS Office Expert",
    "feature.dataEntry": "Data Entry",
    "feature.documentFormatting": "Document Formatting",
    "feature.spreadsheetManagement": "Spreadsheet Management",
    
    // Graphic Services
    "graphic.logo.title": "Logo Design",
    "graphic.logo.desc": "Memorable logos that define your brand identity.",
    "graphic.brand.title": "Brand Identity",
    "graphic.brand.desc": "Complete visual systems including colors and typography.",
    "graphic.social.title": "Social Media Design",
    "graphic.social.desc": "Engaging content across all platforms.",
    "graphic.banner.title": "Banner & Poster Design",
    "graphic.banner.desc": "Eye-catching visuals for campaigns.",
    "graphic.print.title": "Print Design",
    "graphic.print.desc": "Business cards, brochures, and more.",
    "graphic.consultation.title": "Branding Consultation",
    "graphic.consultation.desc": "Expert guidance for your brand.",
    
    // Video Services
    "video.promo.title": "Promotional Videos",
    "video.promo.desc": "Engaging promo videos for brands and products.",
    "video.reels.title": "Social Media Reels",
    "video.reels.desc": "Short-form content for Instagram & TikTok.",
    "video.motion.title": "Motion Graphics",
    "video.motion.desc": "Animated graphics and visual effects.",
    "video.events.title": "Event Highlights",
    "video.events.desc": "Professional event coverage and highlight reels.",
    
    // Digital Marketing Services
    "dm.socialAds.title": "Social Media Ads",
    "dm.socialAds.desc": "Targeted ads on Facebook, Instagram & more.",
    "dm.googleAds.title": "Google Ads",
    "dm.googleAds.desc": "PPC campaigns that drive qualified traffic.",
    "dm.content.title": "Content Marketing",
    "dm.content.desc": "Strategic content that engages audiences.",
    "dm.leads.title": "Lead Generation",
    "dm.leads.desc": "Convert visitors into paying customers.",
    
    // Computer Services
    "computer.excel.title": "Microsoft Excel",
    "computer.excel.desc": "Advanced spreadsheets, formulas, and data analysis.",
    "computer.word.title": "Microsoft Word",
    "computer.word.desc": "Professional document formatting and editing.",
    "computer.ppt.title": "Microsoft PowerPoint",
    "computer.ppt.desc": "Engaging presentations and slide designs.",
    "computer.data.title": "Data Entry",
    "computer.data.desc": "Fast and accurate data entry services.",
    "computer.doc.title": "Document Processing",
    "computer.doc.desc": "Scanning, printing, and file management.",
    "computer.training.title": "Computer Training",
    "computer.training.desc": "Basic to advanced computer skills training.",
    
    // Contact Page
    "contact.subtitle": "Contact Us",
    "contact.title": "Let's build your",
    "contact.title2": "brand",
    "contact.description": "Ready to transform your ideas into impactful visual experiences? Get in touch with us today.",
    "contact.emailUs": "Email Us",
    "contact.whatsapp": "WhatsApp",
    "contact.getInTouch": "Get in Touch",
    "contact.getInTouchDesc": "Whether you have a question about our services, pricing, or want to start a project, we're ready to help you bring your vision to life.",
    "contact.callUs": "Call us",
    "contact.emailUsLabel": "Email us",
    "contact.location": "Location",
    "contact.locationValue": "Bornali, Rajshahi, Bangladesh – 6000",
    "contact.workingHours": "Working Hours",
    "contact.workingHoursValue": "Sat - Thu: 10:00 AM - 8:00 PM",
    "contact.followUs": "Follow us",
    "contact.visitWebsite": "Visit our website",
    "contact.formTitle": "Start Your Project",
    "contact.formSubtitle": "Get a free consultation",
    "contact.yourName": "Your Name",
    "contact.yourEmail": "Your Email",
    "contact.subject": "Subject",
    "contact.message": "Message",
    "contact.namePlaceholder": "John Doe",
    "contact.emailPlaceholder": "john@example.com",
    "contact.subjectPlaceholder": "Logo Design Project",
    "contact.messagePlaceholder": "Tell us about your project...",
    "contact.submitButton": "Contact AlphaZero",
  },
  bn: {
    // Navbar
    "nav.home": "হোম",
    "nav.about": "আমাদের সম্পর্কে",
    "nav.services": "সেবাসমূহ",
    "nav.work": "আমাদের কাজ",
    "nav.team": "টিম",
    "nav.contact": "যোগাযোগ",
    "nav.startProject": "প্রজেক্ট শুরু করুন",
    
    // Home Page
    "home.badge": "ক্রিয়েটিভ ডিজাইন ও আইটি এজেন্সি",
    "home.title1": "প্রতিটি আইডিয়া শুরু হয়",
    "home.title2": "শূন্য থেকে",
    "home.tagline": "শূন্য থেকে প্রভাব",
    "home.description": "গ্রাফিক ডিজাইন, ওয়েব সলিউশন এবং ভিজ্যুয়াল আইডেন্টিটিতে বিশেষজ্ঞ একটি ক্রিয়েটিভ আইটি এজেন্সি। আমরা ব্র্যান্ডগুলিকে শূন্য থেকে শুরু করে পরিষ্কার, আধুনিক এবং প্রভাবশালী ডিজাইন সলিউশন দিয়ে বৃদ্ধি করতে সাহায্য করি।",
    "home.cta1": "আপনার প্রজেক্ট শুরু করুন",
    "home.cta2": "আমাদের কাজ দেখুন",
    "home.stats.projects": "প্রজেক্ট সম্পন্ন",
    "home.stats.clients": "সন্তুষ্ট ক্লায়েন্ট",
    "home.stats.years": "বছরের অভিজ্ঞতা",
    "home.stats.satisfaction": "ক্লায়েন্ট সন্তুষ্টি",
    "home.expertise": "আমাদের দক্ষতা",
    "home.whatWeDo": "আমরা যা",
    "home.do": "করি",
    "home.expertiseDesc": "আপনার ডিজিটাল উপস্থিতি তৈরি এবং বৃদ্ধি করতে সম্পূর্ণ ক্রিয়েটিভ সেবা",
    "home.whyChoose": "কেন আলফাজিরো বেছে নেবেন",
    "home.builtFor": "তৈরি হয়েছে",
    "home.yourSuccess": "আপনার সাফল্যের জন্য",
    "home.testimonials": "প্রশংসাপত্র",
    "home.whatClientsSay": "আমাদের ক্লায়েন্টরা কি",
    "home.say": "বলেন",
    "home.trustedBy": "উদ্ভাবনী ব্র্যান্ডদের বিশ্বস্ত",
    "home.letsBuild": "চলুন তৈরি করি আপনার",
    "home.brand": "ব্র্যান্ড",
    "home.readyTo": "আপনার ধারণাগুলিকে শক্তিশালী ভিজ্যুয়াল অভিজ্ঞতায় রূপান্তর করতে প্রস্তুত?",
    "home.freeConsultation": "বিনামূল্যে পরামর্শ নিন",
    "home.whatsappUs": "হোয়াটসঅ্যাপ করুন",
    "home.viewAllServices": "সব সেবা দেখুন",
    
    // Services
    "home.service.uiux": "UI/UX ডিজাইন",
    "home.service.uiuxDesc": "ব্যবহারকারীদের পছন্দের স্বজ্ঞাত ইন্টারফেস",
    "home.service.seo": "SEO অপ্টিমাইজেশন",
    "home.service.seoDesc": "আপনার টার্গেট অডিয়েন্স দ্বারা খুঁজে পান",
    "home.service.web": "ওয়েবসাইট ডিজাইন ও ডেভেলপমেন্ট",
    "home.service.webDesc": "দ্রুত, রেসপন্সিভ, আধুনিক ওয়েবসাইট",
    "home.service.ecommerce": "ই-কমার্স সলিউশন",
    "home.service.ecommerceDesc": "শক্তিশালী স্টোর দিয়ে অনলাইনে বিক্রি করুন",
    "home.service.social": "সোশ্যাল মিডিয়া ডিজাইন",
    "home.service.socialDesc": "আকর্ষণীয় কন্টেন্ট যা রূপান্তর করে",
    "home.service.branding": "ব্র্যান্ডিং ও ক্রিয়েটিভ ডিজাইন",
    "home.service.brandingDesc": "স্মরণীয় ব্র্যান্ড আইডেন্টিটি তৈরি করুন",
    
    // Why Choose Us
    "home.why.clean": "পরিষ্কার ও আধুনিক ডিজাইন",
    "home.why.cleanDesc": "তাজা, সমসাময়িক নান্দনিকতা যা আলাদা",
    "home.why.brand": "ব্র্যান্ড-কেন্দ্রিক কৌশল",
    "home.why.brandDesc": "প্রতিটি ডিজাইন আপনার ব্র্যান্ডের অনন্য দৃষ্টিভঙ্গি পরিবেশন করে",
    "home.why.detail": "বিস্তারিত-ভিত্তিক",
    "home.why.detailDesc": "প্রতিটি প্রজেক্টে পিক্সেল-পারফেক্ট বাস্তবায়ন",
    "home.why.client": "ক্লায়েন্ট-প্রথম যোগাযোগ",
    "home.why.clientDesc": "পরিষ্কার, প্রতিক্রিয়াশীল এবং সহযোগিতামূলক প্রক্রিয়া",
    "home.why.zero": "শূন্য থেকে সম্পূর্ণ আইডেন্টিটি",
    "home.why.zeroDesc": "শূন্য থেকে সম্পূর্ণ ব্র্যান্ড সলিউশন",
    
    // About Page
    "about.subtitle": "আমাদের সম্পর্কে",
    "about.title": "আমরা",
    "about.description": "গ্রাফিক ডিজাইন, ব্র্যান্ডিং এবং ভিজ্যুয়াল আইডেন্টিটিতে বিশেষজ্ঞ একটি ক্রিয়েটিভ এজেন্সি। আমরা ব্র্যান্ডগুলিকে শূন্য থেকে শুরু করে পরিষ্কার, আধুনিক এবং প্রভাবশালী ডিজাইন সলিউশন দিয়ে বৃদ্ধি করতে সাহায্য করি।",
    "about.story.badge": "আমাদের যাত্রা",
    "about.story.title": "আলফাজিরোর",
    "about.story.title2": "গল্প",
    "about.story.card1.title": "শূন্য থেকে হিরো",
    "about.story.card1.desc": "আলফাজিরো একটি ক্রিয়েটিভ এজেন্সি যা গ্রাফিক ডিজাইন, ব্র্যান্ডিং এবং ভিজ্যুয়াল আইডেন্টিটিতে বিশেষজ্ঞ। আমরা বিশ্বাস করি প্রতিটি দুর্দান্ত ব্র্যান্ড শূন্য থেকে শুরু হয় — এবং সঠিক দৃষ্টিভঙ্গি এবং বাস্তবায়নের সাথে, এটি স্থায়ী প্রভাব ফেলতে পারে।",
    "about.story.card2.title": "ডিজিটাল উৎকর্ষতার বিকাশ",
    "about.story.card2.desc": "বর্তমানে, আলফাজিরো পেশাদার ডিজাইন সেবা প্রদান করে এবং আইটি ও এআই-চালিত ডিজিটাল সেবার দিকে এগিয়ে যাচ্ছে। আমাদের লক্ষ্য হল ধারণাগুলিকে শক্তিশালী ভিজ্যুয়াল অভিজ্ঞতায় রূপান্তরিত করা যা সত্যিই কাজ করে।",
    "about.story.card3.title": "ক্লায়েন্ট-প্রথম পদ্ধতি",
    "about.story.card3.desc": "আমরা আপনার দৃষ্টিভঙ্গি বোঝা এবং প্রত্যাশা ছাড়িয়ে যাওয়া সমাধান প্রদানকে অগ্রাধিকার দিই। আপনার সাফল্যই আমাদের সাফল্য।",
    "about.tagline": "শূন্য থেকে প্রভাব",
    "about.badge.agency": "ক্রিয়েটিভ এজেন্সি",
    "about.whyChoose": "কেন আলফাজিরো বেছে নেবেন?",
    "about.why1": "পরিষ্কার এবং আধুনিক ডিজাইন পদ্ধতি",
    "about.why2": "ব্র্যান্ড-কেন্দ্রিক ভিজ্যুয়াল কৌশল",
    "about.why3": "বিস্তারিত-ভিত্তিক কর্মপ্রবাহ",
    "about.why4": "ক্লায়েন্ট-প্রথম যোগাযোগ",
    "about.why5": "শূন্য থেকে সম্পূর্ণ আইডেন্টিটি সাপোর্ট",
    "about.values.title": "আমাদের মূল্যবোধ",
    "about.values.subtitle": "যে নীতিগুলি আমাদের সমস্ত কাজকে গাইড করে",
    "about.values.brandFocused": "ব্র্যান্ড-কেন্দ্রিক",
    "about.values.brandFocusedDesc": "প্রতিটি ডিজাইন সিদ্ধান্ত আপনার ব্র্যান্ডের অনন্য পরিচয় এবং লক্ষ্যগুলিকে পরিবেশন করে।",
    "about.values.zeroToImpact": "শূন্য থেকে প্রভাব",
    "about.values.zeroToImpactDesc": "আমরা শূন্য থেকে শুরু করি এবং শক্তিশালী, প্রভাবশালী ভিজ্যুয়াল আইডেন্টিটি তৈরি করি।",
    "about.values.globalReach": "বৈশ্বিক পরিধি",
    "about.values.globalReachDesc": "বাংলাদেশে অবস্থিত, বিশ্বব্যাপী ডিজাইন সমাধান প্রদান করছি।",
    "about.location.title": "বাংলাদেশে অবস্থিত",
    "about.location.address": "বর্ণালী, রাজশাহী, বাংলাদেশ – ৬০০০",
    "about.location.desc": "বিশ্বব্যাপী ক্লায়েন্টদের সাথে কাজ করছি, দূর থেকে প্রভাবশালী ডিজাইন সমাধান প্রদান করছি।",
    "about.location.cta1": "যোগাযোগ করুন",
    "about.location.cta2": "হোয়াটসঅ্যাপ করুন",
    
    // Team Page
    "team.subtitle": "আমাদের টিম",
    "team.title": "পরিচয় হোক",
    "team.title2": "নির্মাতাদের",
    "team.description": "ডিজাইনার এবং ডেভেলপারদের একটি উৎসাহী দল আপনার দৃষ্টিভঙ্গিকে জীবন্ত করতে নিবেদিত।",
    "team.join.title": "আমাদের টিমে যোগ দিতে চান?",
    "team.join.desc": "আমরা সবসময় প্রতিভাবান ব্যক্তিদের খুঁজছি আমাদের ক্রিয়েটিভ পরিবারে যোগ দিতে।",
    "team.join.cta1": "আবেদন করুন",
    "team.join.cta2": "যোগাযোগ করুন",
    
    // Footer
    "footer.description": "আলফাজিরো একটি ক্রিয়েটিভ ডিজাইন এজেন্সি যা আধুনিক ভিজ্যুয়াল আইডেন্টিটি এবং ব্র্যান্ড অভিজ্ঞতা তৈরি করে। শূন্য থেকে প্রভাব।",
    "footer.quickLinks": "দ্রুত লিংক",
    "footer.contact": "যোগাযোগ",
    "footer.rights": "সর্বস্বত্ব সংরক্ষিত।",
    "footer.ready": "তৈরি করতে প্রস্তুত?",
    "footer.letsCreate": "আসুন একসাথে কিছু",
    "footer.together": "অসাধারণ তৈরি করি",
    "footer.navigation": "নেভিগেশন",
    "footer.social": "সোশ্যাল",
    
    // Common
    "common.learnMore": "আরও জানুন",
    "common.viewAll": "সব দেখুন",
    
    // Services Page
    "services.subtitle": "আমাদের সেবাসমূহ",
    "services.title": "ফুল-স্ট্যাক",
    "services.title2": "ক্রিয়েটিভ",
    "services.title3": "সেবাসমূহ",
    "services.description": "ডিজাইন থেকে ডেভেলপমেন্ট পর্যন্ত, আমরা আপনার ডিজিটাল উপস্থিতি তৈরি এবং বৃদ্ধি করতে সম্পূর্ণ সমাধান প্রদান করি।",
    "services.whatWeOffer": "আমরা কী অফার করি",
    "services.whatWeOfferDesc": "আপনার ব্র্যান্ডকে শূন্য থেকে প্রভাবে নিয়ে যেতে ডিজাইন করা এজেন্সি-স্তরের সেবা",
    "services.graphicDesign": "গ্রাফিক ডিজাইন সেবা",
    "services.videoEditing": "ভিডিও এডিটিং সেবা",
    "services.digitalMarketing": "ডিজিটাল মার্কেটিং সেবা",
    "services.computerOperation": "কম্পিউটার অপারেশন সেবা",
    "services.process.title": "আমাদের প্রক্রিয়া",
    "services.process.desc": "প্রভাবশালী ফলাফল প্রদানের জন্য একটি সহজ, কার্যকর পদ্ধতি",
    "services.process.discover": "আবিষ্কার",
    "services.process.discoverDesc": "আপনার ব্র্যান্ড, লক্ষ্য এবং দৃষ্টিভঙ্গি বোঝা",
    "services.process.design": "ডিজাইন",
    "services.process.designDesc": "ধারণা এবং ভিজ্যুয়াল সমাধান তৈরি",
    "services.process.develop": "ডেভেলপ",
    "services.process.developDesc": "যত্ন এবং সূক্ষ্মতার সাথে তৈরি",
    "services.process.deliver": "ডেলিভার",
    "services.process.deliverDesc": "চূড়ান্ত ফাইল এবং চলমান সহায়তা",
    "services.cta.title": "আপনার প্রজেক্ট শুরু করতে প্রস্তুত?",
    "services.cta.desc": "আসুন আলোচনা করি কীভাবে আমরা আপনার দৃষ্টিভঙ্গিকে জীবন্ত করতে সাহায্য করতে পারি।",
    "services.cta.button": "বিনামূল্যে পরামর্শ নিন",
    "services.cta.whatsapp": "হোয়াটসঅ্যাপ করুন",
    
    // Service Items
    "service.uiux.title": "UI/UX ডিজাইন",
    "service.uiux.desc": "ব্যবহারকারীদের আনন্দিত করে এবং রূপান্তর বাড়ায় এমন স্বজ্ঞাত, ব্যবহারকারী-কেন্দ্রিক ইন্টারফেস তৈরি করুন।",
    "service.seo.title": "SEO অপ্টিমাইজেশন",
    "service.seo.desc": "ডেটা-চালিত কৌশল দিয়ে আপনার দৃশ্যমানতা বাড়ান এবং সার্চ ইঞ্জিনে উচ্চতর র‍্যাংক করুন।",
    "service.web.title": "ওয়েবসাইট ডিজাইন ও ডেভেলপমেন্ট",
    "service.web.desc": "দ্রুত, রেসপন্সিভ এবং আধুনিক ওয়েবসাইট তৈরি করুন যা আপনার ব্র্যান্ডকে নিখুঁতভাবে উপস্থাপন করে।",
    "service.ecommerce.title": "ই-কমার্স ওয়েবসাইট ডিজাইন",
    "service.ecommerce.desc": "শক্তিশালী, রূপান্তর-কেন্দ্রিক ই-কমার্স সমাধান দিয়ে আপনার অনলাইন স্টোর চালু করুন।",
    "service.social.title": "সোশ্যাল মিডিয়া ডিজাইন ও ম্যানেজমেন্ট",
    "service.social.desc": "আকর্ষণীয় কন্টেন্ট তৈরি করুন যা কমিউনিটি তৈরি করে এবং ব্র্যান্ড সচেতনতা বাড়ায়।",
    "service.branding.title": "ব্র্যান্ডিং ও ক্রিয়েটিভ ডিজাইন",
    "service.branding.desc": "স্মরণীয় ব্র্যান্ড পরিচয় তৈরি করুন যা বাজারে আলাদা।",
    "service.video.title": "ভিডিও এডিটিং",
    "service.video.desc": "প্রমোশনাল, সোশ্যাল মিডিয়া এবং কর্পোরেট কন্টেন্টের জন্য পেশাদার ভিডিও এডিটিং সেবা।",
    "service.marketing.title": "ডিজিটাল মার্কেটিং",
    "service.marketing.desc": "ফলাফল-চালিত কৌশলগত ডিজিটাল মার্কেটিং ক্যাম্পেইন দিয়ে আপনার ব্যবসা বাড়ান।",
    "service.computer.title": "কম্পিউটার অপারেশন",
    "service.computer.desc": "MS Office, ডেটা এন্ট্রি এবং ডকুমেন্ট ম্যানেজমেন্ট সহ বিশেষজ্ঞ কম্পিউটার অপারেশন সেবা।",
    
    // Service Features
    "feature.userResearch": "ইউজার রিসার্চ",
    "feature.wireframing": "ওয়্যারফ্রেমিং",
    "feature.prototyping": "প্রোটোটাইপিং",
    "feature.userTesting": "ইউজার টেস্টিং",
    "feature.keywordResearch": "কীওয়ার্ড রিসার্চ",
    "feature.onPageSeo": "অন-পেজ SEO",
    "feature.technicalSeo": "টেকনিক্যাল SEO",
    "feature.analytics": "অ্যানালিটিক্স",
    "feature.customDesign": "কাস্টম ডিজাইন",
    "feature.responsiveLayout": "রেসপন্সিভ লেআউট",
    "feature.cmsIntegration": "CMS ইন্টিগ্রেশন",
    "feature.performance": "পারফরম্যান্স",
    "feature.productCatalog": "প্রোডাক্ট ক্যাটালগ",
    "feature.paymentGateway": "পেমেন্ট গেটওয়ে",
    "feature.inventorySystem": "ইনভেন্টরি সিস্টেম",
    "feature.contentStrategy": "কন্টেন্ট স্ট্র্যাটেজি",
    "feature.postDesign": "পোস্ট ডিজাইন",
    "feature.storyTemplates": "স্টোরি টেমপ্লেট",
    "feature.brandGuidelines": "ব্র্যান্ড গাইডলাইন",
    "feature.logoDesign": "লোগো ডিজাইন",
    "feature.brandIdentity": "ব্র্যান্ড আইডেন্টিটি",
    "feature.styleGuide": "স্টাইল গাইড",
    "feature.marketingMaterials": "মার্কেটিং ম্যাটেরিয়াল",
    "feature.promotionalVideos": "প্রমোশনাল ভিডিও",
    "feature.socialMediaReels": "সোশ্যাল মিডিয়া রিলস",
    "feature.motionGraphics": "মোশন গ্রাফিক্স",
    "feature.colorGrading": "কালার গ্রেডিং",
    "feature.socialMediaAds": "সোশ্যাল মিডিয়া অ্যাডস",
    "feature.googleAds": "গুগল অ্যাডস",
    "feature.emailMarketing": "ইমেইল মার্কেটিং",
    "feature.contentMarketing": "কন্টেন্ট মার্কেটিং",
    "feature.msOfficeExpert": "MS Office এক্সপার্ট",
    "feature.dataEntry": "ডেটা এন্ট্রি",
    "feature.documentFormatting": "ডকুমেন্ট ফরম্যাটিং",
    "feature.spreadsheetManagement": "স্প্রেডশীট ম্যানেজমেন্ট",
    
    // Graphic Services
    "graphic.logo.title": "লোগো ডিজাইন",
    "graphic.logo.desc": "স্মরণীয় লোগো যা আপনার ব্র্যান্ড পরিচয় নির্ধারণ করে।",
    "graphic.brand.title": "ব্র্যান্ড আইডেন্টিটি",
    "graphic.brand.desc": "রং এবং টাইপোগ্রাফি সহ সম্পূর্ণ ভিজ্যুয়াল সিস্টেম।",
    "graphic.social.title": "সোশ্যাল মিডিয়া ডিজাইন",
    "graphic.social.desc": "সমস্ত প্ল্যাটফর্মে আকর্ষণীয় কন্টেন্ট।",
    "graphic.banner.title": "ব্যানার ও পোস্টার ডিজাইন",
    "graphic.banner.desc": "ক্যাম্পেইনের জন্য নজরকাড়া ভিজ্যুয়াল।",
    "graphic.print.title": "প্রিন্ট ডিজাইন",
    "graphic.print.desc": "বিজনেস কার্ড, ব্রোশিউর এবং আরও অনেক কিছু।",
    "graphic.consultation.title": "ব্র্যান্ডিং পরামর্শ",
    "graphic.consultation.desc": "আপনার ব্র্যান্ডের জন্য বিশেষজ্ঞ গাইডেন্স।",
    
    // Video Services
    "video.promo.title": "প্রমোশনাল ভিডিও",
    "video.promo.desc": "ব্র্যান্ড এবং পণ্যের জন্য আকর্ষণীয় প্রমো ভিডিও।",
    "video.reels.title": "সোশ্যাল মিডিয়া রিলস",
    "video.reels.desc": "Instagram ও TikTok এর জন্য শর্ট-ফর্ম কন্টেন্ট।",
    "video.motion.title": "মোশন গ্রাফিক্স",
    "video.motion.desc": "অ্যানিমেটেড গ্রাফিক্স এবং ভিজ্যুয়াল ইফেক্ট।",
    "video.events.title": "ইভেন্ট হাইলাইটস",
    "video.events.desc": "পেশাদার ইভেন্ট কভারেজ এবং হাইলাইট রিলস।",
    
    // Digital Marketing Services
    "dm.socialAds.title": "সোশ্যাল মিডিয়া অ্যাডস",
    "dm.socialAds.desc": "Facebook, Instagram এবং আরও অনেক কিছুতে টার্গেটেড অ্যাডস।",
    "dm.googleAds.title": "গুগল অ্যাডস",
    "dm.googleAds.desc": "PPC ক্যাম্পেইন যা যোগ্য ট্রাফিক চালায়।",
    "dm.content.title": "কন্টেন্ট মার্কেটিং",
    "dm.content.desc": "কৌশলগত কন্টেন্ট যা অডিয়েন্সকে আকৃষ্ট করে।",
    "dm.leads.title": "লিড জেনারেশন",
    "dm.leads.desc": "ভিজিটরদের পেইং কাস্টমারে রূপান্তর করুন।",
    
    // Computer Services
    "computer.excel.title": "মাইক্রোসফট এক্সেল",
    "computer.excel.desc": "উন্নত স্প্রেডশীট, ফর্মুলা এবং ডেটা বিশ্লেষণ।",
    "computer.word.title": "মাইক্রোসফট ওয়ার্ড",
    "computer.word.desc": "পেশাদার ডকুমেন্ট ফরম্যাটিং এবং এডিটিং।",
    "computer.ppt.title": "মাইক্রোসফট পাওয়ারপয়েন্ট",
    "computer.ppt.desc": "আকর্ষণীয় প্রেজেন্টেশন এবং স্লাইড ডিজাইন।",
    "computer.data.title": "ডেটা এন্ট্রি",
    "computer.data.desc": "দ্রুত এবং সঠিক ডেটা এন্ট্রি সেবা।",
    "computer.doc.title": "ডকুমেন্ট প্রসেসিং",
    "computer.doc.desc": "স্ক্যানিং, প্রিন্টিং এবং ফাইল ম্যানেজমেন্ট।",
    "computer.training.title": "কম্পিউটার ট্রেনিং",
    "computer.training.desc": "বেসিক থেকে উন্নত কম্পিউটার স্কিল ট্রেনিং।",
    
    // Contact Page
    "contact.subtitle": "যোগাযোগ করুন",
    "contact.title": "চলুন তৈরি করি আপনার",
    "contact.title2": "ব্র্যান্ড",
    "contact.description": "আপনার ধারণাগুলোকে প্রভাবশালী ভিজ্যুয়াল অভিজ্ঞতায় রূপান্তর করতে প্রস্তুত? আজই আমাদের সাথে যোগাযোগ করুন।",
    "contact.emailUs": "ইমেইল করুন",
    "contact.whatsapp": "হোয়াটসঅ্যাপ",
    "contact.getInTouch": "যোগাযোগ করুন",
    "contact.getInTouchDesc": "আমাদের সেবা, মূল্য সম্পর্কে প্রশ্ন থাকলে বা একটি প্রজেক্ট শুরু করতে চাইলে, আমরা আপনার দৃষ্টিভঙ্গিকে জীবন্ত করতে প্রস্তুত।",
    "contact.callUs": "কল করুন",
    "contact.emailUsLabel": "ইমেইল করুন",
    "contact.location": "অবস্থান",
    "contact.locationValue": "বর্ণালী, রাজশাহী, বাংলাদেশ – ৬০০০",
    "contact.workingHours": "কাজের সময়",
    "contact.workingHoursValue": "শনি - বৃহস্পতি: সকাল ১০:০০ - রাত ৮:০০",
    "contact.followUs": "আমাদের ফলো করুন",
    "contact.visitWebsite": "আমাদের ওয়েবসাইট দেখুন",
    "contact.formTitle": "আপনার প্রজেক্ট শুরু করুন",
    "contact.formSubtitle": "বিনামূল্যে পরামর্শ নিন",
    "contact.yourName": "আপনার নাম",
    "contact.yourEmail": "আপনার ইমেইল",
    "contact.subject": "বিষয়",
    "contact.message": "বার্তা",
    "contact.namePlaceholder": "আপনার নাম লিখুন",
    "contact.emailPlaceholder": "আপনার ইমেইল লিখুন",
    "contact.subjectPlaceholder": "লোগো ডিজাইন প্রজেক্ট",
    "contact.messagePlaceholder": "আপনার প্রজেক্ট সম্পর্কে বলুন...",
    "contact.submitButton": "আলফাজিরোতে যোগাযোগ করুন",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
    // Apply Bengali fonts when language is Bengali
    if (language === 'bn') {
      document.documentElement.classList.add('font-bengali');
    } else {
      document.documentElement.classList.remove('font-bengali');
    }
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
